const data = {
  products: [
    'Dairy Equipments',
    'Milk Processing Plant',
    'Curd Making Plant',
    'Milk Pasteurization Units',
    'Milk Condensing Machine',
    'Milk And Dairy Plant',
    'Dairy Products Making Machine',
    'Chilling Plant',
  ],
  sub_products: [
    [
      'Mini Dairy Plant',
      'Paneer Press Machine',
      'Curd Production From Milk',
      'Paneer Making Machine',
      'Milk Pasteurization Process',
      'Stainless Steel Dairy Tank',
      'Curd Processing Unit',
    ],
    [
      'Industrial Milk Processing Plant',
      'Mini Milk Processing Plant',
      'Dairy Milk Processing Plant',
      'Curd Processing Plant',
    ],
    [
      'Commercial Curd Making Plant',
      'Dairy Curd Making Plant',
      'Curd For Plant',
      'Curd Making Plant',
      'Mini Curd Making Plant',
    ],
    ['Milk Pasteurization Unit', 'Milk Pasteurization', 'Milk Pasteurisation'],
    ['500 LPH Milk Condensing Machine'],
    ['Curd Incubation Process', 'Milk Processing Plant'],
    ['Ghee Vat Making Machine'],
    ['Instant Milk Chilling Plant'],
  ],
  product_details: [
    [
      {
        name: 'Mini Dairy Plant',
        category: 'Dairy Equipments',
        image: '/products/a1.png',
        price: 500000,
        countInStocks: 10,
        ratings: 4.5,
        numReviews: 10,
        details: [
          [
            'Capacity',
            'Machine Body Material',
            'Automation Grade',
            'Voltage',
            'Material Grade	',
          ],
          [
            '1000 litres/hr',
            'Stainless Steel',
            '	Semi-Automatic',
            '	340 V',
            'SS302',
          ],
        ],
        description:
          'Banking on the skills of our qualified team of professionals, we are instrumental in offering a supreme quality range of Mini Dairy Plant.',
        additional_information: [],
      },
      ,
      {
        name: 'Paneer Press Machine',
        category: 'Dairy Equipments',
        image: '../products/a2.png',
        price: 40000,
        countInStocks: 10,
        ratings: 3.5,
        numReviews: 6,
        details: [
          [
            'Usage/Application',
            'Packaging Type',
            'Capacity',
            'Equipment Type ',
            'Material',
            'Machine Body Material',
            'Brand',
            'Design Type',
            'Automatic Grade',
            'Automation Grade',
            'Height',
            'Operated By',
            'Orientation',
            'Type',
            'Voltage  ',
          ],
          [
            'Milk',
            'Wood',
            '20 - 100 Kgs',
            'Paneer Press Machine',
            'Stainless Steel',
            'Stainless Steel',
            'Company name',
            'Customized',
            'Semi - Automatic',
            'Semi - Automatic',
            'Default',
            'Automatic',
            'Horizontal',
            'Air Pneumatic',
            '220 V',
          ],
        ],
        description:
          'In order to keep pace with the never-ending demands of customers, we are involved in offering a wide range of Paneer Press Machine.',
        additional_information: [
          'Item Code: 002',
          'Production Capacity: 20 - 100 Kgs',
          "Delivery Time: 1'Week",
          'Packaging Details: wood',
        ],
      },
      {
        name: 'Curd Production From Milk',
        category: 'Dairy Equipments',
        image: '../products/a3.png',
        price: 300000,
        countInStocks: 15,
        ratings: 4,
        numReviews: 23,
        details: [
          [
            'Capacity',
            'Operation Mode',
            'Automation Grade',
            'Country of Origin	',
          ],
          [
            '415',
            'Semi-Automatic, Manual, Automatic',
            'Semi-Automatic',
            'Made in India',
          ],
        ],
        description: '',
        additional_information: [],
      },
      {
        name: 'Paneer Making Machine',
        category: 'Dairy Equipments',
        image: '../products/a4.png',
        price: 5000000,
        countInStocks: 15,
        ratings: 4,
        numReviews: 23,
        details: [
          ['Design Type', 'Automation Grade', 'In Deal In'],
          ['Standard', 'Semi-Automatic', 'New Only'],
        ],
        description: '',
        additional_information: [],
      },
      {
        name: 'Milk Pasteurization Process',
        category: 'Dairy Equipments',
        image: '../products/a5.png',
        price: 2000000,
        countInStocks: 15,
        ratings: 4,
        numReviews: 23,
        details: [
          ['Design Type', 'Automation Grade', 'Country of Origin	'],
          ['Customized, Standard', 'Semi-Automatic', 'Made in India'],
        ],
        description: '',
        additional_information: [],
      },
      {
        name: 'Stainless Steel Dairy Tank',
        category: 'Dairy Equipments',
        image: '../products/a6.png',
        price: 40000,
        countInStocks: 15,
        ratings: 4,
        numReviews: 17,
        details: [
          [
            'Usage/Application',
            'Storage Material',
            'Size	Customized',
            'Materials',
            'Brand',
            'Material',
            'Steel Grade',
            'Country of Origin	',
          ],
          [
            'Storage',
            'Water, Milk/Dairy, Milk',
            'Stainless Steel & MS',
            'Company name',
            'Stainless Steel',
            'SS316, SS304, SS304L, MS',
            'Made in India',
            'Made in India',
          ],
        ],
        description:
          'Leveraging the skills of our qualified team of professionals, we are instrumental in offering a wide range of Stainless Steel Dairy Tank.',
        additional_information: [
          'Item Code: 003',
          'Production Capacity: Customized',
          "Delivery Time: 1'Week",
          'Packaging Details: Wood',
        ],
      },
      {
        name: 'Curd Processing Unit',
        category: 'Dairy Equipments',
        image: '../products/a7.png',
        price: 2000000,
        countInStocks: 15,
        ratings: 4,
        numReviews: 3,
        details: [
          ['Design Type","Automation Grade","Country of Origin'],
          ['Standard', 'Semi-Automatic', 'Made in India'],
        ],
        description: '',
        additional_information: [],
      },
    ],
  ],
};

export default data;
