const data = {
  products: [
    {
      name: 'Dairy Equipments',
      product_details: [
        {
          name: 'Mini Dairy Plant',
          category: 'Dairy Equipments',
          image: '/products/a1.png',
          price: 500000,
          countInStocks: 10,
          ratings: 4.5,
          numReviews: 10,
          details: [
            [
              'Capacity',
              'Machine Body Material',
              'Automation Grade',
              'Voltage',
              'Material Grade	',
            ],
            [
              '1000 litres/hr',
              'Stainless Steel',
              '	Semi-Automatic',
              '	340 V',
              'SS302',
            ],
          ],
          description:
            'Banking on the skills of our qualified team of professionals, we are instrumental in offering a supreme quality range of Mini Dairy Plant.',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },

        {
          name: 'Paneer Press Machine',
          category: 'Dairy Equipments',
          image: '../products/a2.png',
          price: 40000,
          countInStocks: 10,
          ratings: 3.5,
          numReviews: 6,
          details: [
            [
              'Usage/Application',
              'Packaging Type',
              'Capacity',
              'Equipment Type ',
              'Material',
              'Machine Body Material',
              'Brand',
              'Design Type',
              'Automatic Grade',
              'Automation Grade',
              'Height',
              'Operated By',
              'Orientation',
              'Type',
              'Voltage  ',
            ],
            [
              'Milk',
              'Wood',
              '20 - 100 Kgs',
              'Paneer Press Machine',
              'Stainless Steel',
              'Stainless Steel',
              'Company name',
              'Customized',
              'Semi - Automatic',
              'Semi - Automatic',
              'Default',
              'Automatic',
              'Horizontal',
              'Air Pneumatic',
              '220 V',
            ],
          ],
          description:
            'In order to keep pace with the never-ending demands of customers, we are involved in offering a wide range of Paneer Press Machine.',
          additional_information: [
            'Item Code: 002',
            'Production Capacity: 20 - 100 Kgs',
            "Delivery Time: 1'Week",
            'Packaging Details: wood',
          ],
          likes: 4,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Curd Production From Milk',
          category: 'Dairy Equipments',
          image: '../products/a3.png',
          price: 300000,
          countInStocks: 15,
          ratings: 3.5,
          numReviews: 27,
          details: [
            [
              'Capacity',
              'Operation Mode',
              'Automation Grade',
              'Country of Origin	',
            ],
            [
              '415',
              'Semi-Automatic, Manual, Automatic',
              'Semi-Automatic',
              'Made in India',
            ],
          ],
          description: '',
          additional_information: [],
          likes: 11,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Paneer Making Machine',
          category: 'Dairy Equipments',
          image: '../products/a4.png',
          price: 5000000,
          countInStocks: 15,
          ratings: 4,
          numReviews: 23,
          details: [
            ['Design Type', 'Automation Grade', 'In Deal In'],
            ['Standard', 'Semi-Automatic', 'New Only'],
          ],
          description: '',
          additional_information: [],
          likes: 22,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Milk Pasteurization Process',
          category: 'Dairy Equipments',
          image: '../products/a5.png',
          price: 2000000,
          countInStocks: 15,
          ratings: 1.5,
          numReviews: 1,
          details: [
            ['Design Type', 'Automation Grade', 'Country of Origin	'],
            ['Customized, Standard', 'Semi-Automatic', 'Made in India'],
          ],
          description: '',
          additional_information: [],
          likes: 8,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Stainless Steel Dairy Tank',
          category: 'Dairy Equipments',
          image: '../products/a6.png',
          price: 40000,
          countInStocks: 15,
          ratings: 2.5,
          numReviews: 17,
          details: [
            [
              'Usage/Application',
              'Storage Material',
              'Size	Customized',
              'Materials',
              'Brand',
              'Material',
              'Steel Grade',
              'Country of Origin	',
            ],
            [
              'Storage',
              'Water, Milk/Dairy, Milk',
              'Stainless Steel & MS',
              'Company name',
              'Stainless Steel',
              'SS316, SS304, SS304L, MS',
              'Made in India',
              'Made in India',
            ],
          ],
          description:
            'Leveraging the skills of our qualified team of professionals, we are instrumental in offering a wide range of Stainless Steel Dairy Tank.',
          additional_information: [
            'Item Code: 003',
            'Production Capacity: Customized',
            "Delivery Time: 1'Week",
            'Packaging Details: Wood',
          ],
          likes: 16,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Curd Processing Unit',
          category: 'Dairy Equipments',
          image: '../products/a7.png',
          price: 2000000,
          countInStocks: 15,
          ratings: 3,
          numReviews: 3,
          details: [
            ['Design Type', 'Automation Grade', 'Country of Origin'],
            ['Standard', 'Semi-Automatic', 'Made in India'],
          ],
          description: '',
          additional_information: [],
          likes: 10,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/a1.png',
            '/products/a2.png',
            '/products/a3.png',
            '/products/a4.png',
            '/products/a5.png',
            '/products/a6.png',
            '/products/a7.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Pioneers in the industry, we offer Mini Dairy Plant, Paneer Press Machine, Curd Production From Milk, Paneer Making Machine, Milk Pasteurization Process and Stainless Steel Dairy Tank from India.',
    },
    {
      name: 'Milk Processing Plant',
      product_details: [
        {
          name: 'Industrial Milk Processing Plant',
          category: 'Milk Processing Plant',
          image: '/products/b1.png',
          price: 4000000,
          countInStocks: 10,
          ratings: 4.5,
          numReviews: 10,
          details: [
            [
              'Equipment Type',
              'Capacity',
              'Material',
              'Automation Grade',
              'Phase',
              'Voltage',
              'I Deal In',
              'Condition',
              'Brand',
              'Country of Origin	',
            ],
            [
              'Milk Pasteurizer',
              '1000 litres/hr',
              'Stainless Steel',
              'Semi-Automatic',
              'Single Phase',
              '415 V',
              'New and Second Hand',
              'New',
              'Company Name',
              'Made in India',
            ],
          ],
          description:
            'Enriched by our vast industrial experience in this business, we are involved in offering an enormous quality range of Industrial Milk Processing Plant.',
          additional_information: [
            'Item Code: 001',
            'Production Capacity: 300 Liter to 200000 Liter',
            "Delivery Time: 4'weeks",
            'Packaging Details: Wood',
          ],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },

        {
          name: 'Mini Milk Processing Plant',
          category: 'Milk Processing Plant',
          image: '../products/b2.png',
          price: 1500000,
          countInStocks: 10,
          ratings: 3.5,
          numReviews: 6,
          details: [
            [
              'Equipment Type',
              'Automatic Grade',
              'Capacity',
              'Phase',
              'Motor Power',
              'Frequency Hz',
              'Voltage V	',
            ],
            [
              'Milk Chillers',
              'Semi-Automatic',
              '1000 litres/hr',
              'Single Phase',
              '4 HP',
              '50 Hz',
              '340V',
            ],
          ],
          description:
            'To meet the various requirements of the customers, we are involved in offering a wide assortment of Mini Milk Processing Plant.',
          additional_information: [],
          likes: 4,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Dairy Milk Processing Plant',
          category: 'Milk Processing Plant',
          image: '../products/b3.png',
          price: 2000000,
          countInStocks: 10,
          ratings: 2.5,
          numReviews: 13,
          details: [
            [
              'Capacity',
              'Material',
              'Product Range',
              'Automation Grade',
              'Phase',
              'Customization	',
            ],
            [
              '1000 litres/hr',
              'Stainless Steel',
              'Toned Milk, Skimmed Milk, Flavoured Milk',
              'Semi-Automatic',
              'Single Phase',
              'Customized',
            ],
          ],
          description:
            'Our company has gained name and fame in presenting Dairy Milk Processing Plant.',
          additional_information: [],
          likes: 29,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Curd Processing Plant',
          category: 'Milk Processing Plant',
          image: '../products/b4.png',
          price: 150000,
          countInStocks: 16,
          ratings: 4,
          numReviews: 9,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 14,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/b1.png',
            '/products/b2.png',
            '/products/b3.png',
            '/products/b4.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Providing you the best range of Industrial Milk Processing Plant, Mini Milk Processing Plant, Dairy Milk Processing Plant and Curd Processing Plant with effective & timely delivery.',
    },
    {
      name: 'Curd Making Plant',
      product_details: [
        {
          name: 'Commercial Curd Making Plant',
          category: 'Curd Making Plant',
          image: '/products/c1.png',
          price: 700000,
          countInStocks: 10,
          ratings: 4.5,
          numReviews: 10,
          details: [
            [
              'Operation Mode',
              'Material',
              'Brand',
              'Condition',
              'Frequency Hz',
              'Voltage	',
            ],
            [
              'Semi-Automatic',
              'Stainless Steel',
              'Company Name',
              'New',
              '50Hz',
              '240V',
            ],
          ],
          description:
            'Owing to the wide experience in this domain, we are instrumental in offering Commercial Curd Making Plant to our clients.',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },

        {
          name: 'Dairy Curd Making Plant',
          category: 'Curd Making Plant',
          image: '../products/c2.png',
          price: 700000,
          countInStocks: 10,
          ratings: 3.5,
          numReviews: 6,
          details: [
            ['Operation Mode', 'Voltage', 'Frequency', 'Brand'],
            ['Semi-Automatic', '240V', '50Hz', 'Company Name'],
          ],
          description:
            'Leveraging the skills of our qualified team of professionals, we are instrumental in offering a wide range of Dairy Curd Making Plant.',
          additional_information: [],
          likes: 4,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Curd For Plant',
          category: 'Curd Making Plant',
          image: '../products/c3.png',
          price: 650000,
          countInStocks: 10,
          ratings: 2.5,
          numReviews: 13,
          details: [['Country of Origin'], ['	Made in India']],
          description: '',
          additional_information: [],
          likes: 29,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Curd Making Plant',
          category: 'Curd Making Plant',
          image: '../products/c4.png',
          price: 1000000,
          countInStocks: 16,
          ratings: 4,
          numReviews: 9,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 14,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Mini Curd Making Plant',
          category: 'Curd Making Plant',
          image: '../products/c5.png',
          price: 600000,
          countInStocks: 11,
          ratings: 4,
          numReviews: 14,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/c1.png',
            '/products/c2.png',
            '/products/c3.png',
            '/products/c4.png',
            '/products/c5.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Offering you a complete choice of products which include Commercial Curd Making Plant, Dairy Curd Making Plant, Curd For Plant, Curd Making Plant and Mini Curd Making Plant.',
    },
    {
      name: 'Milk Pasteurization Units',
      product_details: [
        {
          name: 'Milk Pasteurization Unit',
          category: 'Milk Pasteurization Units',
          image: '../products/d1.png',
          price: 250000,
          countInStocks: 11,
          ratings: 4,
          numReviews: 14,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Milk Pasteurization',
          category: 'Milk Pasteurization Units',
          image: '../products/d2.png',
          price: 700000,
          countInStocks: 6,
          ratings: 3.5,
          numReviews: 14,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 12,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Milk Pasteurisation',
          category: 'Milk Pasteurization Units',
          image: '../products/d3.png',
          price: 150000,
          countInStocks: 4,
          ratings: 2,
          numReviews: 17,
          details: [['Country of Origin'], ['Made in India']],
          description: '',
          additional_information: [],
          likes: 3,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: [
            '/products/d1.png',
            '/products/d2.png',
            '/products/d3.png',
          ],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Our range of products include Milk Pasteurization Unit, Milk Pasteurization and Milk Pasteurisation.',
    },
    {
      name: 'Milk Condensing Machine',
      product_details: [
        {
          name: '500 LPH Milk Condensing Machine',
          category: 'Milk Condensing Machine',
          image: '../products/e1.png',
          price: 2500000,
          countInStocks: 4,
          ratings: 4.5,
          numReviews: 17,
          details: [
            [
              'Capacity',
              'Design Type',
              'Machine Body Material',
              'Automatic Grade',
              'Material',
              'Phase',
              'Voltage',
              'Cooling Temp.',
              'Weight',
              'Product Type',
              'Power Supply',
              'Finishing',
              'Condition',
              'Brand	',
            ],
            [
              '500 litres/hr,500LPH',
              'Customized',
              'SS',
              'Semi-Automatic',
              'SS 304 & SS 316',
              '3',
              '440',
              "4'C",
              '2.5 ton',
              'Milk',
              '10 Hp',
              'C',
              'New',
              'Own',
            ],
          ],
          description:
            'We have a highly acknowledged organization engaged in presenting a remarkable range of 500LPH Milk Condensing Machine.',
          additional_information: [],
          likes: 36,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: ['/products/e1.png'],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: ['/products/e1.png'],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Prominent & Leading Manufacturer from Namakkal, we offer 500LPH Milk Condensing Machine.',
    },
    {
      name: 'Milk And Dairy Plant',
      product_details: [
        {
          name: 'Curd Incubation Process',
          category: 'Milk And Dairy Plant',
          image: '../products/f1.png',
          price: 200000,
          countInStocks: 11,
          ratings: 4,
          numReviews: 14,
          details: [
            ['Equipment Type', 'Capacity', 'Country of Origin'],
            ['Milk Pasteurizer', '500 litres/hr', 'Made in India'],
          ],
          description: '',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: ['/products/f1.png', '/products/f2.png'],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: ['/products/f1.png', '/products/f2.png'],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
        {
          name: 'Milk Processing Plant',
          category: 'Milk And Dairy Plant',
          image: '../products/f2.png',
          price: 1000000,
          countInStocks: 6,
          ratings: 3.5,
          numReviews: 14,
          details: [['Country of Origin'], ['Made in India']],
          description: 'Milk Processing Plant',
          additional_information: [],
          likes: 12,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: ['/products/f1.png', '/products/f2.png'],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: ['/products/f1.png', '/products/f2.png'],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Manufacturer of a wide range of products which include Curd Incubation Process and Milk Processing Plant.',
    },
    {
      name: 'Dairy Products Making Machine',
      product_details: [
        {
          name: 'Ghee Vat Making Machine',
          category: 'Dairy Products Making Machine',
          image: '../products/g1.png',
          price: 80000,
          countInStocks: 11,
          ratings: 4,
          numReviews: 14,
          details: [
            [
              'Design Type',
              'Machine Body Material',
              'Automatic Grade',
              'Ac Power Supply Voltage',
              'Operating Temperature Range',
              'Frequency Hz',
            ],
            [
              'Customized',
              'Stainless Steel',
              'Semi-Automatic',
              '340 V',
              '-45 Degree C',
              '50 Hz',
            ],
          ],
          description:
            'Matching up with the requirements of our clients, we are involved in offering Khoya Making Machine.',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: ['/products/g1.png'],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: ['/products/g1.png'],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Leading Manufacturer of Ghee Vat Making Machine from Namakkal.',
    },
    {
      name: 'Chilling Plant',
      product_details: [
        {
          name: 'Instant Milk Chilling Plant',
          category: 'Chilling Plant',
          image: '../products/h1.png',
          price: 700000,
          countInStocks: 11,
          ratings: 4,
          numReviews: 14,
          details: [
            ['Design Type', 'Machine Body Material', 'Brand', 'Finish'],
            ['Customized', 'Stainless Steel', 'Company Name', 'Powder Coated'],
          ],
          description:
            'In order to keep pace with the never-ending demands of customers, we are involved in offering a wide range of Instant Milk Chilling Plant.',
          additional_information: [],
          likes: 19,
          sub_product: [
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
            {
              name: 'Mini Dairy Plant',
              category: 'Dairy Equipments',
              image: '/products/a1.png',
              price: 500000,
              countInStocks: 10,
              ratings: 4.5,
              numReviews: 10,
            },
          ],
          related_image: ['/products/h1.png'],
          related_video: ['/products/machine_video.mp4'],
          related_blueprint: ['/products/h1.png'],
          comments: [
            {
              name: 'Kavin',
              date: '27.03.2023',
              time: '11.45 pm',
              text: 'Hello This product is nice😝',
              likes: 4,
            },
            {
              name: 'Janu',
              date: '24.03.2023',
              time: '09.45 am',
              text: 'Hello This product is wonderful😁',
              likes: 2,
            },
            {
              name: 'Keerthi',
              date: '29.03.2023',
              time: '10.12 pm',
              text: 'Hello This product is good🤠',
              likes: 1,
            },
          ],
        },
      ],
      description:
        'Offering you a complete choice of products which include Instant Milk Chilling Plant.',
    },
  ],
};

export default data;
